[package]
name = "firefoxpwa-background"
version = "0.0.0"
edition = "2021"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
tauri-winrt-notification = { version = "0.6.0", default-features = false }
trayicon = { version = "0.2.0", default-features = false }
winit = { version = "0.30.5", default-features = false }
